### ISSUE TITLE
Textual improvement on 'TED0: Have you met Ted?'

### ISSUE THREAD

**Issue by Appeltabak** [mauvm/twofliesinoneclap.com#3]
I'v read the first article on the project Ted, which I'm much excited about, and I was notified by @OrangeTux to this repository. Hereby I take the opportunity to suggest a text improvement to which I think enhances readability on the blogpost 'Have you met Ted? '. If you don't prefer such suggestions, please let me know and I won't bother you again :)

Under 'Goals':

> I’ve to descide what display server and GUI library to use.

Besides the typo (`descide -> decide`), I would add 'yet', like this:

> I’ve yet to decide what display server and GUI library to use.

Other 'flaws` have already been fixed, as I saw. Keep up the good work!

**Comment by OrangeTux** [comment]
Thanks for reporting.
