### ISSUE TITLE
Improvements and suggestions on 'TED1: OBD-II, ELM327 and Python'

### ISSUE THREAD

**Issue by Appeltabak** [mauvm/twofliesinoneclap.com#4]
### Under 'OBD':

> So the OBD interface can be used obtain all kinds of information about the car. 
- [x] I suggest inserting 'to' between 'used' and 'obtain'.

> A big list of PID’s can be found on Wikipedia.

The link should redirect to a Wikipedia page about OBD PIDS but instead routes to this page: http://twofliesinoneclap.com/post/obd-ii-elm327-and-python/pid

> Each parameter has his own ID (PID).

Probably it's just me, but when I first read this, I resolved the abbreviation as Process identifier, which is something totally different ;p Making `...his own Paramater ID` would maybe avoid confusion.

> Location of OBD-II connector in Smart Forfour.

Little bit redundant I think, as this sentence is located just above the picture with caption saying the same thing.

> Car manufactorers can choose out of 5 procotols yo speak over the OBD-II interface.
- [x] `manufactorers -> manufacturers` 
- [x] `procotols -> protocols`
- [x] `yo -> to`

> The app markets for Android and iOS contain several apps for displaying car info while. I’ve tested my adapter...
- [x] Ending the sentence with `while` doesn't seem right.
### Under 'ELM372'

> This chip acts as a proxy between the you and the OBD-II connector.
- [ ] Is `the` before `you` intended?
### Python-OBD
- After plugging in in my laptop (and starting the engine) 
- [ ] Duplicate `in`
### Code example

>  # execute_command(commands[1][13]
>  # execute_command(commands['SPEED']
- [ ] Missing ending parenthesis in comments.

**Comment by OrangeTux** [comment]
Thanks for reporting.
